global: # Locally these values are fine but we tipically increase this to 30s if it get's heavy on the server
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: project-poseidon
    metrics_path: /metrics
    static_configs:
      - targets:
          - poseidon:9464
        labels:
          source: docker-compose
          server: local-beta-server
      - targets:
          - host.docker.internal:9464
          - 172.17.0.1:9464
        labels:
          source: host-network-fallback
          server: local-beta-server
